### ISSUE TITLE
Enable `sort-imports`

### ISSUE THREAD

**Issue by WikiRik** [madkingsag/eslint-config#40]
Not sure in which file to place it and if we want it enabled for all files so I'm creating an issue instead.

I would like to enable the [`sort-imports`](https://eslint.org/docs/latest/rules/sort-imports) rule, especially the [`ignoreMemberSort`](https://eslint.org/docs/latest/rules/sort-imports#ignoremembersort) option.

That will give an error when using something like the following;
```ts
import {sequelize, beforeAll2} from '../support'
```

And instead sort the imports to
```ts
import {beforeAll2, sequelize} from '../support'
```

**Comment by ephys** [comment]
I've added `sort-imports` with `ignoreDeclarationSort: false`. `import/order` continues to handle sorting imports, but `sort-imports` will handle sorting members

I've also added `import-newlines`, to enforce single-line imports when possible, and clean multi-line imports when not
